---
kind: pipeline
type: exec
name: 🚀 CI

platform:
  os: linux
  arch: amd64

steps:
  - name: 🛠️ Build
    commands:
      - make build

  - name: 🧪 Test
    commands:
      - make test

  - name: ☂ Cover
    commands:
      - make run-cover

trigger:
  branch:
    - main
  event:
    - tag
    - push
    - pull_request

---
kind: pipeline
name: 🥳 Done

steps:
  - name: 🔔 Notify
    image: plugins/webhook
    settings:
      urls:
        - https://msgbus.mills.io/ci.mills.io

depends_on:
  - 🚀 CI

trigger:
  branch:
    - main
  event:
    - tag
    - push
    - pull_request

