---
kind: pipeline
type: exec
name: 🚀 CI

platform:
  os: linux
  arch: amd64

steps:
  - name: 🛠️ Build
    commands:
      - make build

  - name: 🧪 Test
    commands:
      - make test

trigger:
  branch:
    - main
  event:
    - tag
    - push
    - pull_request

---
kind: pipeline
name: 🐳 Docker

steps:
  - name: 📦 Image
    image: plugins/kaniko
    settings:
      repo: prologic/saltyim
      tags: latest
      build_args:
        - VERSION=latest
        - COMMIT=${DRONE_COMMIT_SHA:0:8}
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
    when:
      branch:
        - main
      event:
        - push

depends_on:
  - 🚀 CI

trigger:
  branch:
    - main
  event:
    - push

---
kind: pipeline
name: 🥳 Done

steps:
  - name: 🔔 Notify
    image: plugins/webhook
    settings:
      urls:
        - https://msgbus.mills.io/ci.mills.io

depends_on:
  - 🚀 CI
  - 🐳 Docker

trigger:
  branch:
    - main
  event:
    - tag
    - push
    - pull_request

